name: ClassConnect
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  gsheets: ^0.4.2
  uuid: ^3.0.7
  fluttertoast: ^8.1.1
  flutter_native_splash: ^2.2.17
  google_fonts: ^3.0.1
  get_it:
  flutter_bloc:
  connectivity_plus: ^3.0.2
  dropdown_textfield: ^1.0.7
  intl_phone_number_input: ^0.7.1
  hive:
  hive_flutter:
  injectable: ^2.1.0
  freezed_annotation: ^2.2.0
  multiple_result: ^4.0.0
  http: ^0.13.5
  flutter_otp_text_field: ^1.1.1

dev_dependencies:
  build_runner:
  hive_generator:
  freezed: ^2.3.2
  injectable_generator:
  lint: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/

